name: resource-awareness
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - lightning>=2.6.1
  - matplotlib>=3.10.8
  - mlflow>=3.10.1
  - pytorch>=2.10.0
  - jupyterlab
  - pip
  - pip:
    - lamarr-energy-tracker
    - -e .
